name: Kauri
main: dev.brighten.anticheat.Kauri
description: You won't see this nibba.
author: "funkemunky"
depend: [Atlas]
api-version: "1.13"
version: ${project.version}
permissions:
  kauri.bypass:
    default: false
    description: Bypass kauri.
  kauri.bypass.ban:
    default: false
    description: Bypass bans.
