# The Kauri 2.0.6 Main Config.
punishments:
# All commands will in this list be run at the same time.
  commands:
    - kick %name% [Kauri] Unfair Advantage -s
# A broadcast message sent when a player gets banned.
# You can set this field to "off" if you do not want a broadcast.
  broadcast: |-
    &8&m-----------------------------------------------------
    &e%name% &7was removed by &6Kauri &7because of an &fUnfair Advantage&7.
    &8&m-----------------------------------------------------
alerts:
# This will send alerts across Bungeecord. No addon is required.
  bungee: false
# The delay in between alerts in milliseconds.
  delay: 500
# You can configure all the checks here.
checks: