on:
  push:
    branches: ["**"]
 
jobs:
  CI/CD:
 
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v1
        with:
          java-version: 17.0
 
      - name: Compile
        run: mvn -B clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Collect artifacts
        uses: actions/upload-artifact@v2
        with:
          name: generated-artifacts
          path: Premium/target/*.jar