on: [push, pull_request]
 
jobs:
  CI:
 
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v1
        with:
          java-version: 17.0
 
      - name: Compile
        run: mvn -B clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Ara
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            Premium/target/Premium-*.jar
            Regular/target/Regular-*.jar
            API/target/API-*.jar